server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: "*" #加载所有的端点，默认只加载了info、health
  endpoint:
    health:
      show-details: always
    shutdown:  #可以关闭指定的端点
      enabled: false

info:
  head: head
  body: body

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8891/eureka/

spring:
  cloud:
    config:
      server:
        git:
          skipSslValidation: true
          uri: https://github.com/jianzaiyu/dis
          search-paths: config-hub
#  rabbitmq:
#    host: rabbitmq


#eureka:
#  instance:
#    hostname: config
#    prefer-ip-address: true
#    metadata-map:
#      user.name: ${security.user.name}
#      user.password: ${security.user.password}
#  client:
#    service-url:
#      defaultZone: http://${srping.security.user.name}:${REGISTRY_SERVER_PASSWORD:password}@registry:8888/eureka/