server:
  port: 8999

spring:
  cloud:
    config:
      server:
        git:
          uri: http://git.300.cn/gongshuyang/cloud.git
          search-paths: config-hub
#  rabbitmq:
#    host: rabbitmq


#eureka:
#  instance:
#    hostname: config
#    prefer-ip-address: true
#    metadata-map:
#      user.name: ${security.user.name}
#      user.password: ${security.user.password}
#  client:
#    service-url:
#      defaultZone: http://${srping.security.user.name}:${REGISTRY_SERVER_PASSWORD:password}@registry:8888/eureka/