spring:
  security:
    user:
      name: user
      password: password

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
          user.name: ${security.user.name}
          user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8001/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  #OkToRetryOnAllOperations: true  #默认为false,则只允许GET请求被重试
  #retryableStatusCodes: 404,502 返回404,502的时候，进行重试，其他状态码不重试
  #ribbonTimeout = (ribbon.ConnectTimeout + ribbon.ReadTimeout) * (ribbon.MaxAutoRetries + 1) * (ribbon.MaxAutoRetriesNextServer + 1);


management:
  endpoints:
    web:
      exposure:
        include: "*" #加载所有的端点，默认只加载了info、health
  endpoint:
    health:
      show-details: always
    shutdown:  #可以关闭指定的端点
      enabled: false

info:
  head: head
  body: body